AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: sam-app

Resources:
  CredicorpApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Cors: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CrediCorpUsersPool.Arn
            Identity:
              Header: Authorization
              ReauthorizeEvery: 30
            ProviderARNs:
              - !GetAtt CrediCorpUsersPool.Arn
            AuthorizationScopes:
              - credicorp-test/read
              - credicorp-test/write

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.10
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref CredicorpApi
            Path: /users/helloWorld
            Method: get

  CrediCorpUsersPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: CrediCorpUsersPool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: True
          RequireNumbers: True
          RequireSymbols: True
          RequireUppercase: True
          TemporaryPasswordValidityDays: 7

  CrediCorpResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      Identifier: credicorp-test
      Name: credicorp-test
      UserPoolId: !Ref CrediCorpUsersPool
      Scopes:
        - ScopeName: read
          ScopeDescription: Read Access
        - ScopeName: write
          ScopeDescription: Write Access

  CredicorpUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: CredicorpUserPoolClient
      GenerateSecret: True
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      UserPoolId: !Ref CrediCorpUsersPool
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthScopes:
        - credicorp-test/read
        - credicorp-test/write

  CredicorpCognitoPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: credicorp-test
      UserPoolId: !Ref CrediCorpUsersPool
